# GROUP 10: University of Vienna – Business Intelligence 1

In [1]:
import pandas as pd

In [2]:
income_data = pd.read_csv("../data/raw/vie-bez-biz-ecn-inc-sex-2002f.csv", sep=";", skiprows=1)
unemployment_data = pd.read_csv("../data/raw/vie-bez-biz-emp-sex-uep-2002f.csv", sep=";", skiprows=1)

In [3]:
income_data.head()

,NUTS,DISTRICT_CODE,SUB_DISTRICT_CODE,REF_YEAR,REF_DATE,INC_TOT_VALUE,INC_MAL_VALUE,INC_FEM_VALUE,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
0,AT13,90000,90000,2002,20021231,18.217,20.709,15.424,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AT13,90100,90100,2002,20021231,25.463,31.961,18.536,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AT13,90200,90200,2002,20021231,16.439,18.301,14.282,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AT13,90300,90300,2002,20021231,18.701,21.444,15.804,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AT13,90400,90400,2002,20021231,20.325,23.641,16.876,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
unemployment_data.head()

,NUTS,DISTRICT_CODE,SUB_DISTRICT_CODE,REF_YEAR,REF_DATE,SEX,UEP_VALUE,UEP_DENSITY,Unnamed: 8,Unnamed: 9
0,AT13,90000,90000,2002,2002,0,74.894,"67,83",NaN,NaN
1,AT13,90100,90100,2002,2002,0,433.000,"35,32",NaN,NaN
2,AT13,90200,90200,2002,2002,0,4.784,"76,98",NaN,NaN
3,AT13,90300,90300,2002,2002,0,3.957,"68,25",NaN,NaN
4,AT13,90400,90400,2002,2002,0,1.140,"55,68",NaN,NaN

## Data Transformation and Integration

### Dim_Sex

Makes no sense to have it as a dim table, it only consists of the value "sex"

In [6]:
dim_sex_data = {
    'SexID':["m", "f"],
    'SexName':["Male", "Female"],
}
dim_sex_df = pd.DataFrame(dim_sex_data)
dim_sex_df.to_csv('../data/created/dim_sex_data.csv', sep=';', index=False),

### Dim_Time

Makes no sense to have it as a dim table, it only consists of the value "year"

### Dim_District

## Data Cleaning